name: PHILO CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unit-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: make
              run: cd philo && make
            - name: make unit-tests
              run: cd philo && make unit-tests
